name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start nginx containe
        run: docker build -t html-server-image . && docker run -d -p 80:80 html-server-image
      - name: ping server
        uses: satak/webrequest-action@master
        with:
          url: 0.0.0.0:80
          method: GET
