name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start nginx containe
        run: docker build -t html-server-image . && docker run -d -p 80:80 html-server-image
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: localhost
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
