name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start nginx containe
        run: docker build -t html-server-image . && docker run -d -p 8080:80 html-server-image
      - name: Run E2E
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: http://0.0.0.0:8080
          method: 'GET'
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
