name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start nginx containe
        run: docker build -t html-server-image . && docker run -d -p 8080:80 html-server-image

      - name: checkout
        uses: actions/checkout@checkout@v2
        with:
          repository: magnuslundstrom/codecept
          ref: refs/heads/main
        run: npm install && npm run codeceptjs:headless
